### PR TITLE
PR for #15

### PR DESCRIPTION
**Pull request by r3lgar**

### CODE REVIEW

**Comment by r3lgar** [comment]
There may be typos.

Also look at lines 40-47 and line 44.

**Comment by r3lgar** [comment]
(rebase because of typo)

**Comment by r3lgar** [comment]
(rebased because of typo)

**Comment by r3lgar** [comment]
@endaaman 
>CONFIGURATION table's layout will broken in a narrow window.

It's because of `nroff`'s table can't wrap text in columns. I can format this section as in `OPTIONS`.

>There are two `allow_bold_font` rows, and two have different descriptions.

Woops. I started writing this section from my config, then copy from `README.md`.

>color_bold is missed in README.md. I added it, so please change `???` to `-`

I think it needs description.

>color_0 .. color_255 is old spec. Now only color_0 .. color_15 is supported. I fixed it in README.md, so please fix it in the same way.

OK.

**Comment by endaaman** [comment]
Nice. I am glad if you would format it.

A value of  `color_bold` is passed to [vte_terminal_set_color_bold](https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-set-color-bold). You can check its behavior by followings

```
$ tym --c:color_bold=blue
```

and

```
$ echo -e '\033[1mbold\033[0m normal'
```

Certainly, I also think this option is confusing. At the same time I think that I want to make it un-documented than to explicitly describe this option that I do not know who needs.

**Comment by endaaman** [comment]
Great. Your manpage will be included in the package (v1.0.9) from the next release.

**Pull request merged**
