### PR TITLE
LuaJIT support

### PR DESCRIPTION
**Pull request by thalting**
TODO: turn this into a build flag.

### CODE REVIEW

**Comment by endaaman** [comment]
Thanks for the PR.

I think this should be the compile option to enbale by like  `--enable-luajit`.

**Comment by thalting** [comment]
how can I do this?

**Comment by endaaman** [comment]
What you have to do

- Edit `configure.ac`, introduce `--with-luajit` option and define the flag that luajit is enabled or not.
- Write LuaJIT-supported code along with the flag.
- Fix Dockerfile or add new test suite for LuaJIT compilation.

**Comment by thalting** [comment]
i don't know how to use autotools :/

**Comment by thalting** [comment]
`--enable-luajit` by @capezotte

**Comment by endaaman** [comment]
`--enable-luajit` and `LUAJIT` are defined but it seems LuaJIT is not actually used.

**Comment by thalting** [comment]
foo

**Comment by fP4rad0x** [comment]
merge?

**Comment by endaaman** [comment]
I wanted you to fix the review. Anyway, it is OK. I will fix it.
Thanks for the PR!

**Pull request merged**
